name: pressio-containers

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [ opened, reopened, synchronize ]
    paths:
      - '.github/workflows/ci-docker.yml'
      - 'docker_scripts/**'
  schedule:
    - cron:  '0 5 * * FRI'

jobs:
  CI:
    strategy:
      matrix:
        config:
          - {dockerfile: 'fedora-clang',                   compiler-version: '17', tag: 'latest'}
          - {dockerfile: 'fedora-clang-mpi',               compiler-version: '17', tag: 'latest'}
          - {dockerfile: 'fedora-gnu',                     compiler-version: '13', tag: 'latest'}
          - {dockerfile: 'fedora-gnu-mpi',                 compiler-version: '13', tag: 'latest'}
          # - {dockerfile: 'intel-oneapi',                  compiler-version: 'latest'}
          - {dockerfile: 'ubuntu-clang',                   compiler-version: '14', tag: 'latest'}
          - {dockerfile: 'ubuntu-clang-mpi',               compiler-version: '14', tag: 'latest'}
          - {dockerfile: 'ubuntu-gnu-trilinos',            compiler-version: '11', tag: '0dc4553'}
          - {dockerfile: 'ubuntu-gnu-trilinos',            compiler-version: '11', tag: '5bbda25'}
          - {dockerfile: 'ubuntu-gnu',                     compiler-version: '11', tag: 'latest'}
          - {dockerfile: 'ubuntu-gnu-mpi',                 compiler-version: '11', tag: 'latest'}
          - {dockerfile: 'ubuntu-gnu-kokkos-cpu-openmp',   compiler-version: '11', tag: 'latest'}
          - {dockerfile: 'ubuntu-gnu-kokkos-cpu-serial',   compiler-version: '11', tag: 'latest'}

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Construct Docker image name
        run: |
          IMAGE_NAME=$(echo ${{ matrix.config.dockerfile }} | sed -E 's/^([^-]+)-([^-]+)/\1-\2${{ matrix.config.compiler-version }}/')
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker images for Github Container Registry
        uses: docker/build-push-action@v6
        with:
          tags: ghcr.io/pressio/${{ env.IMAGE_NAME }}:${{ matrix.config.tag }}
          file: docker_scripts/${{ matrix.config.dockerfile }}.dockerfile
          build-args: |
            COMPILER_VERSION=${{ matrix.config.compiler-version }}
            DOCKER_TAG=${{ matrix.config.tag }}
          # Only push image if running on main or develop
          push: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' }}
